name: Android + tmate Terminal (Instant Access)

on:
  workflow_dispatch:
    inputs:
      runtime_minutes:
        description: "Runtime (max 360; default 355)"
        required: false
        default: "355"
      android_api:
        description: "Android API level (29, 30, 31, 33, 34)"
        required: false
        default: "30"

permissions:
  contents: read

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 370

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager --install "platform-tools" "platforms;android-${{ inputs.android_api }}"
          sdkmanager --install "system-images;android-${{ inputs.android_api }};google_apis;x86_64"
          sdkmanager --install "emulator"
          sdkmanager --install "build-tools;34.0.0"
          
          echo "✅ Android SDK installed"

      - name: Setup tmate session (Terminal Access)
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false
          timeout-minutes: ${{ inputs.runtime_minutes }}

      - name: Keep alive
        run: |
          echo "Session ended"
