name: macOS VNC via ZeroTier (prompt version)

on:
  workflow_dispatch:
    inputs:
      vnc_password:
        description: "VNC password (first 8 chars used)"
        required: true
        default: "Bullet@12345"
      zerotier_network:
        description: "ZeroTier Network ID"
        required: true

jobs:
  vnc:
    runs-on: macos-latest
    steps:
      - name: Install TigerVNC and dependencies
        run: |
          set -euo pipefail
          brew install tigervnc || true

      - name: Set VNC password and start server (port 5900)
        run: |
          set -euo pipefail
          mkdir -p ~/.vnc
          echo "${{ inputs.vnc_password }}" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          nohup vncserver :0 -rfbport 5900 -SecurityTypes VncAuth &

      - name: Install and join ZeroTier
        run: |
          set -euo pipefail
          curl -s https://install.zerotier.com | bash
          sudo zerotier-cli join "${{ inputs.zerotier_network }}"

      - name: Wait for ZeroTier IP and show connect info
        run: |
          set -euo pipefail
          sleep 25
          ip=$(ifconfig | grep -Eo "172\.[0-9]+\.[0-9]+\.[0-9]+")
          echo "✅ Connect using any VNC client:"
          echo "Address: ${ip}:5900"
          echo "Password: ${{ inputs.vnc_password }}"
          echo "Recommended clients: Mocha VNC Lite (Android), RealVNC, Screens (Mac/iOS)."
