name: macOS VNC via ZeroTier (fixed password)

on:
  workflow_dispatch:

jobs:
  vnc:
    runs-on: macos-latest
    steps:
      - name: Download and extract TigerVNC
        run: |
          set -euo pipefail
          curl -L -o /tmp/tigervnc.tar.gz https://sourceforge.net/projects/tigervnc/files/stable/1.13.1/TigerVNC-1.13.1.x86_64-Darwin.tar.gz/download
          tar -xzf /tmp/tigervnc.tar.gz -C /tmp || true

      - name: Set VNC password and start server (port 5900)
        run: |
          set -euo pipefail
          brew install tigervnc || true
          mkdir -p ~/.vnc
          echo "Bullet@12345" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          nohup vncserver :0 -rfbport 5900 -SecurityTypes VncAuth &

      - name: Install and join ZeroTier
        run: |
          set -euo pipefail
          curl -s https://install.zerotier.com | bash
          sudo zerotier-cli join <YOUR_NETWORK_ID>

      - name: Wait for ZeroTier IP and show connect info
        run: |
          set -euo pipefail
          sleep 25
          ip=$(zerotier-cli listpeers; ifconfig | grep -Eo "172\.[0-9]+\.[0-9]+\.[0-9]+")
          echo "✅ Connect using a VNC client:"
          echo "Address: $ip:5900"
          echo "Password: Bullet@12345"
          echo "Recommended client: Mocha VNC Lite (Android)"
