name: Ubuntu VNC via ZeroTier (passwordless)

on:
  workflow_dispatch:
    inputs:
      zerotier_network:
        description: "ZeroTier Network ID (from https://my.zerotier.com)"
        required: true
      runtime_minutes:
        description: "Keep-alive minutes (max 360)"
        required: false
        default: "180"

jobs:
  vnc:
    runs-on: ubuntu-22.04
    timeout-minutes: 370
    steps:
      - name: Install Xfce desktop and TigerVNC (server)
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies tigervnc-standalone-server tigervnc-common xterm
          mkdir -p ~/.vnc
          # Minimal X startup: launch XFCE when VNC connects
          cat > ~/.vnc/xstartup <<'EOS'
#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
startxfce4 &
EOS
          chmod +x ~/.vnc/xstartup
          # Ensure no stale servers
          vncserver -kill :1 >/dev/null 2>&1 || true
          echo "TigerVNC installed."

      - name: Install and join ZeroTier
        run: |
          set -e
          curl -fL https://install.zerotier.com/ -o /tmp/zt.sh
          sudo bash /tmp/zt.sh
          sudo zerotier-cli join "${{ inputs.zerotier_network }}"
          echo "Joined ZeroTier. Authorize this member in your ZeroTier dashboard."

      - name: Wait for ZeroTier IP
        id: ztip
        run: |
          set -e
          ZT_IP=""
          for i in {1..24}; do
            ZT_IP="$(sudo zerotier-cli listnetworks 2>/dev/null | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n1 || true)"
            [ -n "$ZT_IP" ] && break
            sleep 5
          done
          if [ -z "$ZT_IP" ]; then
            echo "No ZeroTier IP yet. Make sure you authorized the node in the dashboard." >&2
            exit 1
          fi
          echo "ZT_IP=$ZT_IP" >> "$GITHUB_ENV"
          echo "ZeroTier IP: $ZT_IP"

      - name: Start TigerVNC (passwordless) on port 5901
        run: |
          set -e
          # Start server with no authentication (only safe inside ZeroTier)
          vncserver -kill :1 >/dev/null 2>&1 || true
          vncserver :1 -geometry 1280x720 -SecurityTypes None
          # Verify it is listening
          for i in {1..30}; do
            if ss -ltn | grep -q ':5901'; then
              echo "TigerVNC is listening on 5901."
              break
            fi
            sleep 1
          done
          ss -ltn | grep ':5901' || { echo "VNC did not open port 5901"; exit 1; }

      - name: Show connection info
        run: |
          set -e
          echo "===================================="
          echo "Passwordless VNC is ready:"
          echo " Address : ${ZT_IP}:5901"
          echo " Auth    : None (no password)"
          echo " Client  : RealVNC Viewer, bVNC, etc."
          echo " Note    : Anyone on your ZeroTier network can connect."
          echo "===================================="

      - name: Keep alive
        run: |
          set -e
          rt="${{ inputs.runtime_minutes }}"
          [[ "$rt" =~ ^[0-9]+$ ]] || rt=180
          (( rt > 360 )) && rt=360
          end=$(( $(date +%s) + 60*rt ))
          while (( $(date +%s) < end )); do
            echo "[ZT+TigerVNC passwordless] Heartbeat $(date '+%H:%M:%S') | ${ZT_IP}:5901"
            sleep 60
          done
