name: Ubuntu VNC via ZeroTier (passwordless)

on:
  workflow_dispatch:
    inputs:
      zerotier_network:
        description: "ZeroTier Network ID"
        required: true
      runtime_minutes:
        description: "Keep-alive minutes (<=360)"
        required: false
        default: "180"

jobs:
  vnc:
    runs-on: ubuntu-22.04
    timeout-minutes: 370
    steps:
      - name: Install desktop and TigerVNC
        shell: bash
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies tigervnc-standalone-server tigervnc-common xterm curl
          mkdir -p "$HOME/.vnc"
          printf '%s\n' '#!/bin/sh' 'unset SESSION_MANAGER' 'unset DBUS_SESSION_BUS_ADDRESS' 'startxfce4 &' > "$HOME/.vnc/xstartup"
          chmod +x "$HOME/.vnc/xstartup"
          vncserver -kill :1 >/dev/null 2>&1 || true

      - name: Install and join ZeroTier
        shell: bash
        run: |
          set -e
          curl -fL https://install.zerotier.com/ -o /tmp/zt.sh
          sudo bash /tmp/zt.sh
          sudo zerotier-cli join "${{ inputs.zerotier_network }}"
          echo "Authorize this member in the ZeroTier dashboard."

      - name: Wait for ZeroTier IP
        shell: bash
        run: |
          set -e
          for i in $(seq 1 24); do
            ZT_IP="$(sudo zerotier-cli listnetworks 2>/dev/null | awk '{for(n=1;n<=NF;n++) if ($n ~ /([0-9]{1,3}\.){3}[0-9]{1,3}/){print $n; exit}}')"
            [ -n "$ZT_IP" ] && break
            sleep 5
          done
          [ -n "$ZT_IP" ] || { echo "No ZeroTier IP yet; authorize node first." >&2; exit 1; }
          echo "ZT_IP=$ZT_IP" >> "$GITHUB_ENV"
          echo "ZeroTier IP: $ZT_IP"

      - name: Start TigerVNC passwordless on :1 (5901)
        shell: bash
        run: |
          set -e
          vncserver -kill :1 >/dev/null 2>&1 || true
          vncserver :1 -geometry 1280x720 -SecurityTypes None
          for i in $(seq 1 30); do
            ss -ltn | grep -q ':5901' && { echo "TigerVNC listening on 5901."; break; }
            sleep 1
          done
          ss -ltn | grep -q ':5901' || { echo "VNC did not open port 5901"; exit 1; }

      - name: Show connection info
        shell: bash
        run: |
          echo "===================================="
          echo "Connect from Android/PC VNC client:"
          echo " Address : ${ZT_IP}:5901"
          echo " Auth    : None (no password)"
          echo " Note    : Anyone on your ZeroTier network can connect."
          echo "===================================="

      - name: Keep alive
        shell: bash
        run: |
          set -e
          RT="${{ inputs.runtime_minutes }}"
          echo "$RT" | grep -Eq '^[0-9]+$' || RT=180
          [ "$RT" -gt 360 ] && RT=360
          END=$(( $(date +%s) + RT*60 ))
          while [ "$(date +%s)" -lt "$END" ]; do
            echo "[ZT+TigerVNC passwordless] Heartbeat $(date '+%H:%M:%S') | ${ZT_IP}:5901"
            sleep 60
          done
