name: VNC via ZeroTier (macOS)

on:
  workflow_dispatch:
    inputs:
      zerotier_network:
        description: "Your ZeroTier Network ID (from https://my.zerotier.com)"
        required: true
      vnc_password:
        description: "VNC password (max 8 chars)"
        required: false
        default: "12345678"
      runtime_minutes:
        description: "Keep-alive runtime (max 360 min)"
        required: false
        default: "120"

permissions:
  contents: read

jobs:
  vnc:
    runs-on: macos-13
    timeout-minutes: 370
    steps:
      - name: Enable Screen Sharing (VNC)
        shell: bash
        run: |
          set -euo pipefail
          VNC_PW="${{ inputs.vnc_password }}"
          VNC_PW="${VNC_PW:0:8}"
          KS="/System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart"
          sudo "$KS" -activate -configure -access -on -allowAccessFor -allUsers -restart -agent -menu
          sudo "$KS" -configure -clientopts -setvnclegacy -vnclegacy yes
          sudo "$KS" -configure -setvncpw -vncpw "$VNC_PW"
          nohup caffeinate -dimsu >/tmp/caffeinate.log 2>&1 &

      - name: Install ZeroTier
        shell: bash
        run: |
          set -euo pipefail
          curl -fL https://install.zerotier.com/ -o zt.sh
          sudo bash zt.sh
          sudo zerotier-cli status || true
          sudo zerotier-cli join ${{ inputs.zerotier_network }}
          echo "✅ Joined ZeroTier network: ${{ inputs.zerotier_network }}"
          echo "Wait 15–20s, then authorize this client in your ZeroTier dashboard."

      - name: Show connection info
        shell: bash
        run: |
          echo "=========================================="
          echo "ZeroTier ID:"
          sudo zerotier-cli info | awk '{print $3}'
          echo "------------------------------------------"
          echo "After authorizing in ZeroTier web UI:"
          echo "  → Find this device’s IP (starts with 10.x or 192.x)"
          echo "  → Connect via RealVNC Viewer:"
          echo "      Address: <that ZeroTier IP>:5900"
          echo "      Password: first 8 chars of your input"
          echo "=========================================="

      - name: Keep Alive
        shell: bash
        run: |
          rt="${{ inputs.runtime_minutes }}"
          [[ "$rt" =~ ^[0-9]+$ ]] || rt=120
          (( rt > 360 )) && rt=360
          end=$(( $(date +%s) + 60 * rt ))
          while (( $(date +%s) < end )); do
            now=$(date '+%H:%M:%S')
            echo "[ZeroTier+VNC] Heartbeat $now"
            sleep 60
          done
