name: macOS VNC via ZeroTier + TigerVNC

on:
  workflow_dispatch:
    inputs:
      zerotier_network:
        description: "ZeroTier Network ID from https://my.zerotier.com"
        required: true
      vnc_password:
        description: "VNC password (max 8 chars; extras ignored)"
        required: false
        default: "12345678"
      runtime_minutes:
        description: "Keep-alive runtime (max 360)"
        required: false
        default: "120"

permissions:
  contents: read

jobs:
  vnc:
    runs-on: macos-13
    timeout-minutes: 370
    steps:
      - name: Install TigerVNC and set password
        shell: bash
        run: |
          set -euo pipefail
          brew update >/dev/null
          brew install tiger-vnc >/dev/null
          mkdir -p "$HOME/.vnc"
          VNC_PW="${{ inputs.vnc_password }}"
          VNC_PW="${VNC_PW:0:8}"
          printf '%s\n' "$VNC_PW" | vncpasswd -f > "$HOME/.vnc/passwd"
          chmod 600 "$HOME/.vnc/passwd"
          VNC_BIN="$(command -v vncserver)"
          nohup "$VNC_BIN" -geometry 1280x720 -SecurityTypes VncAuth :1 > "$HOME/vnc.log" 2>&1 &
          sleep 3
          echo "TigerVNC started on display :1 (port 5901)."

      - name: Install and join ZeroTier
        shell: bash
        run: |
          set -euo pipefail
          curl -fL https://install.zerotier.com/ -o zt.sh
          sudo bash zt.sh
          sudo zerotier-cli status || true
          sudo zerotier-cli join "${{ inputs.zerotier_network }}"
          echo "Joined ZeroTier network: ${{ inputs.zerotier_network }}"
          echo "Authorize this runner in the ZeroTier web dashboard."

      - name: Wait for ZeroTier IP
        shell: bash
        run: |
          set -euo pipefail
          for i in {1..18}; do
            IP=$(sudo zerotier-cli listnetworks | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n1 || true)
            if [ -n "$IP" ]; then break; fi
            sleep 5
          done
          if [ -z "$IP" ]; then
            echo "⚠ No ZeroTier IP found — authorize the member in dashboard."
          else
            echo "ZT_IP=$IP" >> "$GITHUB_ENV"
            echo "========================================="
            echo "Connect now with RealVNC or any client:"
            echo " Address : $IP:5901"
            echo " Password: first 8 chars you entered"
            echo "========================================="
          fi

      - name: Keep alive
        shell: bash
        run: |
          rt="${{ inputs.runtime_minutes }}"
          [[ "$rt" =~ ^[0-9]+$ ]] || rt=120
          (( rt > 360 )) && rt=360
          end=$(( $(date +%s) + 60 * rt ))
          while (( $(date +%s) < end )); do
            ts=$(date '+%H:%M:%S')
            echo "[ZeroTier+TigerVNC] Heartbeat $ts | target: ${ZT_IP:-authorize in dashboard}:5901"
            sleep 60
          done
